OBJS = text_binary.o double_point.o cpy.o 
TARGET ?= text
CC ?= gcc
CFLAGS += -O
CFLAGS += -Wall

.SUFFIXES: .c .o

all: $(TARGET)

$(TARGET): $(OBJS)
	   $(CC) $(OBJS) -o $(TARGET) $(CFLAGS)

.c .o:     $<
	   $(CC) -c $< $(CFLAGS)
clean:
	rm -f $(OBJS) $(TARGET)